spring:
  datasource:
    #url: jdbc:mariadb://${ZCP_ESTIMATE_MARIADB_SERVICE_HOST}:${ZCP_ESTIMATE_MARIADB_SERVICE_PORT}/${MARIADB_DATABASE}
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/zcp_estimate
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    dbcp2:
      validation-query: SELECT 1
