apiVersion: v1
kind: Service
metadata:
  name: zcp-estimate-mariadb
spec:
  selector:
    app: zcp-estimate-mariadb
  ports:
  - name: "http"
    port: 3306
    targetPort: 3306
  type: NodePort